version: "3.9"

services:
  db_auth:
    container_name: db_auth
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: pulat
      PGDATA: /var/lib/postgresql/data/pgdata
    image: postgres:14.3-alpine
    volumes:
      - ./data:/var/lib/postgresql/data
  app:
    build: .
    environment:
      POSTGRES_PASSWORD: pulat
      POSTGRES_HOST: db_auth
      BOT_TOKEN: 1380355163:AAHYxMWbQa_mlHwaawi_zXUANoQAInBmEV0
      ADMINS: 732928701,2066041574
      MAILING_TIME: '11:24'
      FROM_TABLE: 1f-qZEX1k_3nj5cahOzntYAnvO4ignbyesVO7yuBdv_g
      TO_TABLE: 1V07vlHGZuWlvvSrLt2LvKKr0yXVQOULnk3q3lZMT22Y
